# Generated by Django 5.2.13 on 2026-04-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='devices_dev_project_7192ad_idx'), models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_device_name_per_project')],
            },
        ),
    ]
